http:
  port: 8080
tikv:
  address: http://ADDRESS:2379
redis:
  address: ADDRESS:6379
  password:
  db: 0
mongo:
  uri: mongodb://ADDRESS:27017
  name: cache-compare
  username: USERNAME
  password: PASSWORD